name: Vite build

on:
  - pull_request
  - workflow_dispatch

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Check build
        run: npm run build
