name: Vite build

on: [pull_request]

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Check build
        run: yarn build
