name: Prettier formatting

on: [pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Check formatting
        run: npm run format:check
