name: Eslint linting

on:
  - pull_request
  - workflow_dispatch

jobs:
  check-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Check linting
        run: npm run lint
