name: Jest test

on: [pull_request]

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Check tests
        run: npm run test
